# action.yml
name: 'TRIVY SCAN'
description: 'SCAN CONTAINER IMAGES WITH TRIVY'
inputs:
    image-name:
         description: name of image to be scanned
outputs:
    scan-result:
        description: result of the trivy scan
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: aquasec/trivy
  args:
    - ${{ inputs.image-name }}
